[trails]
# grid size
grid_size_x = 100
grid_size_y = 100
# nest location (%)
nest_loc_x = 50
nest_loc_y = 50
# initial number of ants
ants_int = 10
# initial number of food locations
food_int = 5
# persistence parameter (i.e. probability that an ant will change direction)
alpha = 0.2
# environmental decay applied to all markers
decay_rate = 0.97