[trails]
# grid size
grid_size_x = 100
grid_size_y = 100
# nest location (%)
nest_loc_x = 50
nest_loc_y = 50
# ant population size
ants_num = 100
# initial number of scout ants
scout_ants = 20
# how many ants are recruited when an ant finds food and returns to the nest
recruitment_rate = 5
# persistence parameter, i.e. probability that an ant will change direction [0-1]
alpha = 0.4
# how many directions the ant can detect markers (must be an odd number to ensure symmetry around the current direction)
detection_range = 5
# environmental decay applied to all markers after each step (multiplicative) [0-1]
marker_decay_rate = 0.01
# drop rate decay rate (multiplicative) [0-1]
drop_rate_decay = 0.01
# sensitivity decay rate (linear) [0-1]
sensitivity_decay = 0.001
# number of food sources
food_num = 5
# how much food can an ant eat at once [0-1]
food_step = 0.01
# number of steps to simulate
steps = 100000
# animation speed (e.g. 100x = grid updates every 100 steps)
speed = 25
# run with visualisation
visualise = false